### ISSUE TITLE
Ltac2 tactics with capital names are uncallable

### ISSUE THREAD

**Issue by JasonGross** [ppedrot/ltac2#14]
```
Ltac2 MyRefine f := Control.refine f.
Ltac2 call_MyRefine f := MyRefine f. (* Error: Unbound constructor MyRefine *)
```

**Comment by ppedrot** [comment]
Oh, that's a bug, the first definition should not let you call the tactic this way. Uppercase names are reserved for identifiers, as in OCaml, that's a valuable syntactic criterion. (The code for arbitrary constructors and patterns in Coq is incredibly complex and un-intuitive, I did not want to go that way.).

**Comment by ppedrot** [comment]
Fixed.
