### ISSUE TITLE
Ltac2 scope cannot be disabled after it is (transitively) required

### ISSUE THREAD

**Issue by JasonGross** [ppedrot/ltac2#15]
`Require Ltac2.Ltac2` should not mean that I need to wrap all of my Ltac1 proofs in `ltac1:()`.  That should only happen if I do `Import Ltac2.Init`.  This bug means that using Ltac2 in a small part of my project is a very invasive change, because any file depending on such theorems needs to wrap all Ltac1 with `ltac1:(...)`.  This can be seen with this example:
```
Require Ltac2.Ltac2.
Goal True -> True.
  intro x. (* Error: Unbound value intro *)
```

**Comment by ppedrot** [comment]
This is a limitation of the current way options work. I will probably craft some ad-hoc workaround. Meanwhile, you can globally reset the proof mode to Ltac1 by setting somewhere `Global Set Default Proof Mode "Classic"`.
