### ISSUE TITLE
More parentheses needed in type printer

### ISSUE THREAD

**Issue by JasonGross** [ppedrot/ltac2#4]
I am trying to figure out what's going wrong with some code of mine, and getting this headache-inducing error message:
```
Error:
This expression has type (ident * Pattern.context) option list * (ident * constr) list but an expression was
expected of type
(ident * Pattern.context) option list * 'b list
```

**Comment by ppedrot** [comment]
It may be the case I messed up with theoretically forbidden one-tuples in ML code, not that the printer is behaving wrongly. Do you have a reproducible example?

**Comment by JasonGross** [comment]
Oh, the issue here is that I have trouble parsing `'a * 'b list`.  I think it means `('a * 'b) list`, and it would be nice if the printer would display it like that (though perhaps this is just something to get used to).

**Comment by ppedrot** [comment]
That's the standard precedence of ML, so I think I'll leave it as is.
