### ISSUE TITLE
Please add backtrace printer or debugger

### ISSUE THREAD

**Issue by JasonGross** [ppedrot/ltac2#7]
I'd like to get a stack trace with something like `Uncaught Ltac2 exception: Match_failure`, or, at least, I'd like to be able to run the tactic in a way (or with options) that gives me such a trace

**Comment by ppedrot** [comment]
By setting the `Ltac2 Backtrace` option, Coq will now print toplevel Ltac2 failures with a backtrace. I did not test it thoroughly though, YMMV.
